### ISSUE TITLE
Mesh Obj Origin to Mesh Obj Origin behavior for Aligned Dims not working

### ISSUE THREAD

**Issue by kevancress** [kevancress/MeasureIt-ARCH#13]
Array iterator out of range: (index 9999999)
Traceback (most recent call last):
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\measureit_arch\measureit_arch_main.py", line 462, in draw_callback_3d
    draw_main_3d(context)
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\measureit_arch\measureit_arch_main.py", line 449, in draw_main_3d
    draw_alignedDimension(context, myobj, DimGen, alignedDim)
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\measureit_arch\measureit_arch_geometry.py", line 226, in draw_alignedDimension
    selectedNormal = Vector(select_normal(myobj,dim,normDistVector,midpoint))
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\measureit_arch\measureit_arch_geometry.py", line 443, in select_normal
    vertA = myobj.data.vertices[dim.dimPointA]
IndexError: bpy_prop_collection[index]: index 9999999 out of range, size 8

**Comment by kevancress** [comment]
Fixed in: d9418d5ca662502b2ac3b85919d4748f25ee2458
