### ISSUE TITLE
Area not displayed + Measureit_ARCH Image traceback

### ISSUE THREAD

**Issue by baldyman01** [kevancress/MeasureIt-ARCH#224]
I downloaded the development code today 7/7. Area's now can be added and deleted but never display in viewport. Trying to Render a MeasureitARCH  image throws the following error -

Python: Traceback (most recent call last):
  File "/home/pete/.config/blender/3.2/scripts/addons/MeasureIt_ARCH-development/measureit_arch_render.py", line 107, in execute
    outpath = render_main(self, context)
  File "/home/pete/.config/blender/3.2/scripts/addons/MeasureIt_ARCH-development/measureit_arch_render.py", line 252, in render_main
    draw3d_loop(context, objlist)
  File "/home/pete/.config/blender/3.2/scripts/addons/MeasureIt_ARCH-development/measureit_arch_geometry.py", line 3613, in draw3d_loop
    draw_areaDimension(context, myobj, DimGen,
  File "/home/pete/.config/blender/3.2/scripts/addons/MeasureIt_ARCH-development/measureit_arch_geometry.py", line 1738, in draw_areaDimension
    placementResults = setup_dim_text(myobj,dim,dimProps, sumArea,origin,vecX,vecY, is_area=True)
  File "/home/pete/.config/blender/3.2/scripts/addons/MeasureIt_ARCH-development/measureit_arch_geometry.py", line 3692, in setup_dim_text
    distanceText = format_area(dist, dim=dim)
TypeError: format_area() got an unexpected keyword argument 'dim'

Blender 3.2.0 Stable
Measureit_ARCH development as of 7/7

**Comment by kevancress** [comment]
Hey @baldyman01 

Thanks for the report, yep looks like I broke the area formatting code when I was adding the option for per-dimension unit overrides.

Should be fixed in 7a2ca40464a5000960f2553a8ae5da965cff3395. Let me know if its working for you!

I still need to get around to fixing some of the other issues with text placement and scaling for area's!

**Comment by baldyman01** [comment]
Yep, this issue is fixed. Nice job!

**Comment by baldyman01** [comment]
I also note that I'm not corrupting existing dimensions by editing the owner object any more. Not sure if it was a deliberate fix, but it's a lot better.

**Comment by kevancress** [comment]
Great! hmm nope I haven't done anything intentional to fix the dims getting corrupted when editing the object vertices... I did clean up how mesh data is handled a little bit a while back, so maybe that's helping... Anyway it may still happen in some cases, but glad that its working better!

Closing this for now, Let me know if anything else comes up!
