### ISSUE TITLE
I enabled the add-on MeasurIt-ARCH included in Blender 2.82 and Blender crashes on startup

### ISSUE THREAD

**Issue by stillpointx** [kevancress/MeasureIt-ARCH#55]
I enabled the add-on MeasurIt-ARCH included in Blender 2.82 and it crashes Blender on startup every-time.
```

    r12t@sys8:~$ /snap/bin/blender 
    Read prefs: /home/r12t/.config/blender/2.82/config/userpref.blend
    /run/user/1000/snap.blender/gvfs/ non-existent directory
    found bundled python: /snap/blender/37/2.82/python
    Fatal Python error: initsite: Failed to import the site module
    Traceback (most recent call last):
      File "/snap/blender/37/2.82/python/lib/python3.7/site.py", line 579, in <module>
        main()
      File "/snap/blender/37/2.82/python/lib/python3.7/site.py", line 562, in main
        known_paths = venv(known_paths)
      File "/snap/blender/37/2.82/python/lib/python3.7/site.py", line 469, in venv
        os.path.join(exe_dir, conf_basename),
    NameError: name 'conf_basename' is not defined
    r12t@sys8:~$ 
```

I'm using Ubuntu 18.04 64bit Linux.
How can I fix this?

**Comment by stillpointx** [comment]
Was a corrupt pref.blend file I deleted it and it started to work again.
